In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import datetime
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('c-rate_regdata.csv')
df

,vin,state,state.1,intime,battcurrent,odometer,soc,cyclenum,bt1,bt2,bt3,bt4,bv1,bv2,bv3,bv4,bv5,bv6,bv7,bv8,bv9,bv10,bv11,bv12,bv13,bv14,bv15,bv16,ampherehour,month,year
0,MB7A8CLLTKJK30385,31,3,2021-01-28 16:54:44.000,0.2,22792.0,15.0,1,19.6,19.2,19.9,19.0,3.309,3.320,3.325,3.325,3.340,3.329,3.327,3.329,3.330,3.306,3.333,3.333,3.337,3.338,3.335,3.353,-0.01,1,2021
1,MB7A8CLLTKJK30385,10,1,2021-01-28 17:30:27.000,0.9,22792.0,15.0,1,19.5,18.7,19.7,18.6,3.311,3.322,3.325,3.325,3.338,3.330,3.327,3.330,3.330,3.306,3.333,3.333,3.337,3.340,3.337,3.349,-0.01,1,2021
2,MB7A8CLLTKJK30385,22,2,2021-01-28 17:32:27.000,14.8,22792.0,95.0,1,19.5,18.8,19.7,18.6,3.378,3.401,3.359,3.375,3.622,3.393,3.411,3.424,3.453,3.340,3.425,3.396,3.456,3.399,3.411,3.636,0.59,1,2021
3,MB7A8CLLTKJK30385,24,2,2021-01-28 17:34:27.000,0.9,22792.0,100.0,1,19.5,18.7,19.7,18.6,3.345,3.377,3.293,3.380,3.541,3.359,3.374,3.409,3.366,3.306,3.399,3.374,3.391,3.390,3.354,3.570,0.59,1,2021
4,MB7A8CLLTKJK30385,10,1,2021-01-28 17:36:27.000,0.9,22792.0,100.0,1,19.4,18.6,19.6,18.6,3.338,3.369,3.290,3.375,3.522,3.354,3.364,3.399,3.416,3.291,3.390,3.359,3.401,3.374,3.348,3.551,0.59,1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2556940,MB7U8CLLTLJB30370,2,0,2021-09-12 17:33:30.000,538.5,4605510.0,51.9,12847,-2778.3,0.0,0.0,0.0,0.130,0.000,5.398,0.000,1.000,22.800,10.130,-28.263,-1.764,9.361,-26.407,6.436,7.573,-27.959,-30.357,-6.248,5.47,9,2021
2556941,MB7U8CLLTLJB30370,2,0,2022-01-04 15:51:08.000,563.3,48.0,51.7,13103,-2779.9,0.0,0.0,0.0,0.129,0.000,5.365,0.008,0.996,26.900,10.899,-28.167,18.722,10.130,-26.903,-1.753,6.546,-27.703,26.937,10.644,5.59,1,2022
2556942,MB7U8CLLTLJB30370,2,0,2022-01-04 15:53:08.000,563.3,48.0,51.7,13103,-2779.9,0.0,0.0,0.0,0.129,0.000,5.365,0.008,0.996,26.900,10.899,-28.167,18.722,10.130,-26.903,-1.753,6.546,-27.703,26.937,10.644,5.59,1,2022
2556943,MB7U8CLLTLJB30370,2,0,2021-09-08 15:52:43.000,538.5,4605488.0,51.8,13596,-2775.1,0.0,0.0,0.0,0.130,0.000,5.383,0.000,0.999,30.991,10.642,-28.215,10.529,10.642,-26.471,-1.751,-0.621,-27.880,18.762,-30.315,7.82,9,2021
2556944,MB7U8CLLTLJB30370,2,0,2021-09-08 15:54:43.000,538.5,4605488.0,51.8,13596,-2775.1,0.0,0.0,0.0,0.130,0.000,5.383,0.000,0.999,30.991,10.642,-28.215,10.529,10.642,-26.471,-1.751,-0.621,-27.880,18.762,-30.315,7.82,9,2021

In [4]:
df.columns
df['state'].unique()

array([ 31,  10,  22,  24,  21,  32,  26,  25,  12, 214,   0,  30, 211,
        13,   1,  20, 215,   3, 219,   8,  11, 210, 115, 125, 130, 231,
        35, 311, 327, 328,  43,  44, 412, 416, 417, 419, 420, 421, 525,
       623, 624, 631,  73,   9,  27, 326, 413, 428,  54, 625,  71, 711,
       723,   5,   2])

In [5]:
df = df[(df['state.1']==3) & (df['battcurrent']<=0)]
df['calc_current'] = df['battcurrent']/144
group_df = df.groupby(['vin','state','cyclenum']).agg({'calc_current':'mean', 'odometer':'min', 'intime':'min'}).reset_index()

/var/folders/my/07f5nb2j5r93lzd5_vt01ztc0000gn/T/ipykernel_60398/3351336547.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['calc_current'] = df['battcurrent']/144

In [6]:
group_df

,vin,state,cyclenum,calc_current,odometer,intime
0,MB7A8CLLTKJK30385,31,1,-0.179902,22792.0,2021-01-28 18:40:27.000
1,MB7A8CLLTKJK30385,31,2,-0.184625,22792.0,2021-02-07 17:05:26.000
2,MB7A8CLLTKJK30385,31,3,-0.199908,26060.0,2021-09-29 21:26:17.000
3,MB7A8CLLTKJK30385,31,4,-0.214350,22802.0,2021-02-09 17:09:41.000
4,MB7A8CLLTKJK30385,31,5,-0.164946,22835.0,2021-02-13 08:36:53.000
...,...,...,...,...,...,...
5830,MB7U8CLLTLJB30370,32,555,-0.045139,38540.0,2021-06-15 14:47:24.000
5831,MB7U8CLLTLJB30370,32,557,-0.022917,38686.0,2021-06-18 22:11:10.000
5832,MB7U8CLLTLJB30370,35,102,-0.268750,67178.0,2022-03-04 10:26:01.000
5833,MB7U8CLLTLJB30370,327,124,-0.009722,68844.0,2022-03-23 20:01:50.000
5834,MB7U8CLLTLJB30370,328,125,-0.377083,48977.0,2021-09-09 16:43:28.000

In [7]:
vin_group = group_df.groupby(['vin'])
type(group_df['intime'][0])

str

In [9]:
vin_group.ngroups
import streamlit as st
# for i in range(0,vin_group.ngroups):
#     with st.container():
#         "c"+str(i) = st.columns((1))

0
1
2
3
4
5
6
7

## filter for derived battcurrent < -0.01
### remove all positive values from battcurrent before taking avg only

In [10]:


def plot(index):

    filtered_df = [vin_group.get_group(x) for x in vin_group.groups][index].copy()
    print(filtered_df)
    vin = filtered_df.vin.unique()[0]
    filtered_df = filtered_df[filtered_df['calc_current'] <= -0.01]
    filtered_df = filtered_df.sort_values('intime').reset_index(drop = True)
    filtered_df['intime'] = pd.to_datetime(filtered_df['intime'], infer_datetime_format=True)
    filtered_df['date'] = filtered_df['intime'].apply(lambda x : str(x.day)+'-'+str(x.month)+'-'+str(x.year))
    fig = px.line(filtered_df, x="date", y="calc_current", title=vin+" battery current TREND")
    fig.show()
    
list(map(plot, range(vin_group.ngroups)))

                   vin  state  cyclenum  calc_current  odometer  \
0    MB7A8CLLTKJK30385     31         1     -0.179902   22792.0
1    MB7A8CLLTKJK30385     31         2     -0.184625   22792.0
2    MB7A8CLLTKJK30385     31         3     -0.199908   26060.0
3    MB7A8CLLTKJK30385     31         4     -0.214350   22802.0
4    MB7A8CLLTKJK30385     31         5     -0.164946   22835.0
..                 ...    ...       ...           ...       ...
525  MB7A8CLLTKJK30385     32       335     -0.004167   22438.0
526  MB7A8CLLTKJK30385     32       336     -0.004167   22509.0
527  MB7A8CLLTKJK30385     32       337     -0.018056   22557.0
528  MB7A8CLLTKJK30385     32       339     -0.006944   22632.0
529  MB7A8CLLTKJK30385     32       341     -0.015278   22725.0

                      intime
0    2021-01-28 18:40:27.000
1    2021-02-07 17:05:26.000
2    2021-09-29 21:26:17.000
3    2021-02-09 17:09:41.000
4    2021-02-13 08:36:53.000
..                       ...
525  2021-01-18 13:10:59.000
526  2021-01-20 10:53:25.000
527  2021-01-21 11:19:49.000
528  2021-01-24 14:06:17.000
529  2021-01-26 17:49:45.000

[530 rows x 6 columns]

AttributeError: 'Figure' object has no attribute 'savefig'